services:
  postgres:
    # use a separate data volume so init scripts run for tests
    volumes:
      - pgdata_test:/var/lib/postgresql/data
      - ./pg-init/01-create-dbs.sql:/docker-entrypoint-initdb.d/01-create-dbs.sql:ro
      - ./pg-init/02-create-test-dbs.sql:/docker-entrypoint-initdb.d/02-create-test-dbs.sql:ro
      - ./pg-init/03-policy-init.sql:/docker-entrypoint-initdb.d/03-policy-init.sql:ro

  policy-svc:
    environment:
      DATABASE_URL: "postgres://wa:wa@postgres:5432/policy_db_test?sslmode=disable"

  leave-api:
    environment:
      DATABASE_URL: "postgresql://wa:wa@postgres:5432/leave_db_test?schema=public"
      POLICY_GRPC_URL: "policy-svc:50051"
      NODE_ENV: "test"

volumes:
  pgdata_test: {}
